name: ukraine_news
description: ウクライナ情報局

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adaptive_dialog: ^1.4.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_markdown: ^0.6.9+1
  flutter_riverpod: ^2.0.0-dev.4
  flutterfire_ui: ^0.3.6+1
  go_router: ^3.0.4
  hooks_riverpod: ^2.0.0-dev.4
  http: ^0.13.4
  settings_ui: ^2.0.2
  url_launcher: ^6.0.20
  webfeed: ^0.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
